server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: '*'
      mvc:
        routes:
          - id: products
            uri: http://localhost:8081
            predicates:
              - Path=/products/**

          - id: orders
            uri: http://localhost:8082
            predicates:
              - Path=/orders/**

          - id: auth
            uri: http://localhost:8083
            predicates:
              - Path=/auth/**

          - id: accounts
            uri: http://localhost:8084
            predicates:
              - Path=/accounts/**
