export const add_product_to_cart = 'cart/addProductToCart'
export const remove_product_from_cart = 'cart/removeProductFromCart'
export const add_product_element_to_cart = 'cart/addProductElementToCart'
export const remove_product_element_from_cart = 'cart/removeProductElementFromCart'
export const clear_cart = 'cart/clearCart'
